<?php
/**
 * SSODefaultApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should not be interpreted as html to avoid unexpected bahavior, like xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.5.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * SSODefaultApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SSODefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'authDefaultSsoProviderGet' => [
            'application/json',
        ],
        'authSaml2IdGet' => [
            'application/json',
        ],
        'authSaml2IdMetadataGet' => [
            'application/json',
        ],
        'authSaml2IdResponsePost' => [
            'application/json',
        ],
        'authSsoCodePost' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation authDefaultSsoProviderGet
     *
     * Get all published sso provider
     *
     * @param  string|null $cursor id of the cursor used for pagination; required if page is set (optional)
     * @param  int|null $limit amount of results per page (1 ... 100) (optional)
     * @param  int|null $page current page index of the cursor used for pagination; required if cursor is set (optional)
     * @param  string|null $accept_language client language(s) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authDefaultSsoProviderGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SsoProviderResponseDefault[]|\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields|\OpenAPI\Client\Model\ModelSwagErrorUnauthorized|\OpenAPI\Client\Model\ModelSwagErrorForbidden|\OpenAPI\Client\Model\ModelSwagErrorInternalServerError
     */
    public function authDefaultSsoProviderGet($cursor = null, $limit = null, $page = null, $accept_language = null, string $contentType = self::contentTypes['authDefaultSsoProviderGet'][0])
    {
        list($response) = $this->authDefaultSsoProviderGetWithHttpInfo($cursor, $limit, $page, $accept_language, $contentType);
        return $response;
    }

    /**
     * Operation authDefaultSsoProviderGetWithHttpInfo
     *
     * Get all published sso provider
     *
     * @param  string|null $cursor id of the cursor used for pagination; required if page is set (optional)
     * @param  int|null $limit amount of results per page (1 ... 100) (optional)
     * @param  int|null $page current page index of the cursor used for pagination; required if cursor is set (optional)
     * @param  string|null $accept_language client language(s) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authDefaultSsoProviderGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SsoProviderResponseDefault[]|\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields|\OpenAPI\Client\Model\ModelSwagErrorUnauthorized|\OpenAPI\Client\Model\ModelSwagErrorForbidden|\OpenAPI\Client\Model\ModelSwagErrorInternalServerError, HTTP status code, HTTP response headers (array of strings)
     */
    public function authDefaultSsoProviderGetWithHttpInfo($cursor = null, $limit = null, $page = null, $accept_language = null, string $contentType = self::contentTypes['authDefaultSsoProviderGet'][0])
    {
        $request = $this->authDefaultSsoProviderGetRequest($cursor, $limit, $page, $accept_language, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SsoProviderResponseDefault[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorUnauthorized',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorForbidden',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorInternalServerError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SsoProviderResponseDefault[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SsoProviderResponseDefault[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorUnauthorized',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorForbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorInternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation authDefaultSsoProviderGetAsync
     *
     * Get all published sso provider
     *
     * @param  string|null $cursor id of the cursor used for pagination; required if page is set (optional)
     * @param  int|null $limit amount of results per page (1 ... 100) (optional)
     * @param  int|null $page current page index of the cursor used for pagination; required if cursor is set (optional)
     * @param  string|null $accept_language client language(s) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authDefaultSsoProviderGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authDefaultSsoProviderGetAsync($cursor = null, $limit = null, $page = null, $accept_language = null, string $contentType = self::contentTypes['authDefaultSsoProviderGet'][0])
    {
        return $this->authDefaultSsoProviderGetAsyncWithHttpInfo($cursor, $limit, $page, $accept_language, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authDefaultSsoProviderGetAsyncWithHttpInfo
     *
     * Get all published sso provider
     *
     * @param  string|null $cursor id of the cursor used for pagination; required if page is set (optional)
     * @param  int|null $limit amount of results per page (1 ... 100) (optional)
     * @param  int|null $page current page index of the cursor used for pagination; required if cursor is set (optional)
     * @param  string|null $accept_language client language(s) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authDefaultSsoProviderGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authDefaultSsoProviderGetAsyncWithHttpInfo($cursor = null, $limit = null, $page = null, $accept_language = null, string $contentType = self::contentTypes['authDefaultSsoProviderGet'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SsoProviderResponseDefault[]';
        $request = $this->authDefaultSsoProviderGetRequest($cursor, $limit, $page, $accept_language, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authDefaultSsoProviderGet'
     *
     * @param  string|null $cursor id of the cursor used for pagination; required if page is set (optional)
     * @param  int|null $limit amount of results per page (1 ... 100) (optional)
     * @param  int|null $page current page index of the cursor used for pagination; required if cursor is set (optional)
     * @param  string|null $accept_language client language(s) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authDefaultSsoProviderGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authDefaultSsoProviderGetRequest($cursor = null, $limit = null, $page = null, $accept_language = null, string $contentType = self::contentTypes['authDefaultSsoProviderGet'][0])
    {






        $resourcePath = '/auth/default/sso-provider';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);

        // header params
        if ($accept_language !== null) {
            $headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue($accept_language);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation authSaml2IdGet
     *
     * Start a saml2 auth flow
     *
     * @param  string $origin the requesting platform (Ios|Android|Web|Cms) (required)
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function authSaml2IdGet($origin, $id, string $contentType = self::contentTypes['authSaml2IdGet'][0])
    {
        $this->authSaml2IdGetWithHttpInfo($origin, $id, $contentType);
    }

    /**
     * Operation authSaml2IdGetWithHttpInfo
     *
     * Start a saml2 auth flow
     *
     * @param  string $origin the requesting platform (Ios|Android|Web|Cms) (required)
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function authSaml2IdGetWithHttpInfo($origin, $id, string $contentType = self::contentTypes['authSaml2IdGet'][0])
    {
        $request = $this->authSaml2IdGetRequest($origin, $id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation authSaml2IdGetAsync
     *
     * Start a saml2 auth flow
     *
     * @param  string $origin the requesting platform (Ios|Android|Web|Cms) (required)
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSaml2IdGetAsync($origin, $id, string $contentType = self::contentTypes['authSaml2IdGet'][0])
    {
        return $this->authSaml2IdGetAsyncWithHttpInfo($origin, $id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authSaml2IdGetAsyncWithHttpInfo
     *
     * Start a saml2 auth flow
     *
     * @param  string $origin the requesting platform (Ios|Android|Web|Cms) (required)
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSaml2IdGetAsyncWithHttpInfo($origin, $id, string $contentType = self::contentTypes['authSaml2IdGet'][0])
    {
        $returnType = '';
        $request = $this->authSaml2IdGetRequest($origin, $id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authSaml2IdGet'
     *
     * @param  string $origin the requesting platform (Ios|Android|Web|Cms) (required)
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authSaml2IdGetRequest($origin, $id, string $contentType = self::contentTypes['authSaml2IdGet'][0])
    {

        // verify the required parameter 'origin' is set
        if ($origin === null || (is_array($origin) && count($origin) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $origin when calling authSaml2IdGet'
            );
        }

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling authSaml2IdGet'
            );
        }


        $resourcePath = '/auth/Saml2/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $origin,
            'origin', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation authSaml2IdMetadataGet
     *
     * Generates a metadata.xml file
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdMetadataGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function authSaml2IdMetadataGet($id, string $contentType = self::contentTypes['authSaml2IdMetadataGet'][0])
    {
        $this->authSaml2IdMetadataGetWithHttpInfo($id, $contentType);
    }

    /**
     * Operation authSaml2IdMetadataGetWithHttpInfo
     *
     * Generates a metadata.xml file
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdMetadataGet'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function authSaml2IdMetadataGetWithHttpInfo($id, string $contentType = self::contentTypes['authSaml2IdMetadataGet'][0])
    {
        $request = $this->authSaml2IdMetadataGetRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorNotFound',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorInternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation authSaml2IdMetadataGetAsync
     *
     * Generates a metadata.xml file
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdMetadataGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSaml2IdMetadataGetAsync($id, string $contentType = self::contentTypes['authSaml2IdMetadataGet'][0])
    {
        return $this->authSaml2IdMetadataGetAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authSaml2IdMetadataGetAsyncWithHttpInfo
     *
     * Generates a metadata.xml file
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdMetadataGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSaml2IdMetadataGetAsyncWithHttpInfo($id, string $contentType = self::contentTypes['authSaml2IdMetadataGet'][0])
    {
        $returnType = '';
        $request = $this->authSaml2IdMetadataGetRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authSaml2IdMetadataGet'
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdMetadataGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authSaml2IdMetadataGetRequest($id, string $contentType = self::contentTypes['authSaml2IdMetadataGet'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling authSaml2IdMetadataGet'
            );
        }


        $resourcePath = '/auth/Saml2/{id}/metadata';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['text/xml', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation authSaml2IdResponsePost
     *
     * Response endpoint of saml2 auth flow
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdResponsePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function authSaml2IdResponsePost($id, string $contentType = self::contentTypes['authSaml2IdResponsePost'][0])
    {
        $this->authSaml2IdResponsePostWithHttpInfo($id, $contentType);
    }

    /**
     * Operation authSaml2IdResponsePostWithHttpInfo
     *
     * Response endpoint of saml2 auth flow
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdResponsePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function authSaml2IdResponsePostWithHttpInfo($id, string $contentType = self::contentTypes['authSaml2IdResponsePost'][0])
    {
        $request = $this->authSaml2IdResponsePostRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];
        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
        

            throw $e;
        }
    }

    /**
     * Operation authSaml2IdResponsePostAsync
     *
     * Response endpoint of saml2 auth flow
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdResponsePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSaml2IdResponsePostAsync($id, string $contentType = self::contentTypes['authSaml2IdResponsePost'][0])
    {
        return $this->authSaml2IdResponsePostAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authSaml2IdResponsePostAsyncWithHttpInfo
     *
     * Response endpoint of saml2 auth flow
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdResponsePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSaml2IdResponsePostAsyncWithHttpInfo($id, string $contentType = self::contentTypes['authSaml2IdResponsePost'][0])
    {
        $returnType = '';
        $request = $this->authSaml2IdResponsePostRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authSaml2IdResponsePost'
     *
     * @param  string $id Provider ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSaml2IdResponsePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authSaml2IdResponsePostRequest($id, string $contentType = self::contentTypes['authSaml2IdResponsePost'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling authSaml2IdResponsePost'
            );
        }


        $resourcePath = '/auth/Saml2/{id}/response';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation authSsoCodePost
     *
     * Create a session based on sso auth code
     *
     * @param  \OpenAPI\Client\Model\SsoCodeRequest $request sso auth code to redeem (required)
     * @param  string|null $platform The client platform (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSsoCodePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\AuthLoginResponse|\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields|\OpenAPI\Client\Model\ModelSwagErrorForbidden|\OpenAPI\Client\Model\ModelSwagErrorNotFound|\OpenAPI\Client\Model\ModelSwagErrorInternalServerError
     */
    public function authSsoCodePost($request, $platform = null, string $contentType = self::contentTypes['authSsoCodePost'][0])
    {
        list($response) = $this->authSsoCodePostWithHttpInfo($request, $platform, $contentType);
        return $response;
    }

    /**
     * Operation authSsoCodePostWithHttpInfo
     *
     * Create a session based on sso auth code
     *
     * @param  \OpenAPI\Client\Model\SsoCodeRequest $request sso auth code to redeem (required)
     * @param  string|null $platform The client platform (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSsoCodePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\AuthLoginResponse|\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields|\OpenAPI\Client\Model\ModelSwagErrorForbidden|\OpenAPI\Client\Model\ModelSwagErrorNotFound|\OpenAPI\Client\Model\ModelSwagErrorInternalServerError, HTTP status code, HTTP response headers (array of strings)
     */
    public function authSsoCodePostWithHttpInfo($request, $platform = null, string $contentType = self::contentTypes['authSsoCodePost'][0])
    {
        $request = $this->authSsoCodePostRequest($request, $platform, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\AuthLoginResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorForbidden',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorNotFound',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\ModelSwagErrorInternalServerError',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\AuthLoginResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AuthLoginResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorBadRequestWithErrorFields',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorForbidden',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorNotFound',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\ModelSwagErrorInternalServerError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation authSsoCodePostAsync
     *
     * Create a session based on sso auth code
     *
     * @param  \OpenAPI\Client\Model\SsoCodeRequest $request sso auth code to redeem (required)
     * @param  string|null $platform The client platform (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSsoCodePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSsoCodePostAsync($request, $platform = null, string $contentType = self::contentTypes['authSsoCodePost'][0])
    {
        return $this->authSsoCodePostAsyncWithHttpInfo($request, $platform, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authSsoCodePostAsyncWithHttpInfo
     *
     * Create a session based on sso auth code
     *
     * @param  \OpenAPI\Client\Model\SsoCodeRequest $request sso auth code to redeem (required)
     * @param  string|null $platform The client platform (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSsoCodePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authSsoCodePostAsyncWithHttpInfo($request, $platform = null, string $contentType = self::contentTypes['authSsoCodePost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AuthLoginResponse';
        $request = $this->authSsoCodePostRequest($request, $platform, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'authSsoCodePost'
     *
     * @param  \OpenAPI\Client\Model\SsoCodeRequest $request sso auth code to redeem (required)
     * @param  string|null $platform The client platform (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['authSsoCodePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authSsoCodePostRequest($request, $platform = null, string $contentType = self::contentTypes['authSsoCodePost'][0])
    {

        // verify the required parameter 'request' is set
        if ($request === null || (is_array($request) && count($request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $request when calling authSsoCodePost'
            );
        }



        $resourcePath = '/auth/sso-code';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($platform !== null) {
            $headerParams['Platform'] = ObjectSerializer::toHeaderValue($platform);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($request));
            } else {
                $httpBody = $request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
