<?php
/**
 * AccountVisibilitySettingsRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should be careful to interpreted them as html to avoid against xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.4.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.19.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AccountVisibilitySettingsRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountVisibilitySettingsRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'account.VisibilitySettingsRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'appointment_visible' => 'bool',
        'chat_visible' => 'bool',
        'email_visible' => 'bool',
        'image_visible' => 'bool',
        'salutation_visible' => 'bool',
        'title_visible' => 'bool',
        'visible_for_others' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'appointment_visible' => null,
        'chat_visible' => null,
        'email_visible' => null,
        'image_visible' => null,
        'salutation_visible' => null,
        'title_visible' => null,
        'visible_for_others' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'appointment_visible' => false,
        'chat_visible' => false,
        'email_visible' => false,
        'image_visible' => false,
        'salutation_visible' => false,
        'title_visible' => false,
        'visible_for_others' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'appointment_visible' => 'appointmentVisible',
        'chat_visible' => 'chatVisible',
        'email_visible' => 'emailVisible',
        'image_visible' => 'imageVisible',
        'salutation_visible' => 'salutationVisible',
        'title_visible' => 'titleVisible',
        'visible_for_others' => 'visibleForOthers'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'appointment_visible' => 'setAppointmentVisible',
        'chat_visible' => 'setChatVisible',
        'email_visible' => 'setEmailVisible',
        'image_visible' => 'setImageVisible',
        'salutation_visible' => 'setSalutationVisible',
        'title_visible' => 'setTitleVisible',
        'visible_for_others' => 'setVisibleForOthers'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'appointment_visible' => 'getAppointmentVisible',
        'chat_visible' => 'getChatVisible',
        'email_visible' => 'getEmailVisible',
        'image_visible' => 'getImageVisible',
        'salutation_visible' => 'getSalutationVisible',
        'title_visible' => 'getTitleVisible',
        'visible_for_others' => 'getVisibleForOthers'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('appointment_visible', $data ?? [], null);
        $this->setIfExists('chat_visible', $data ?? [], null);
        $this->setIfExists('email_visible', $data ?? [], null);
        $this->setIfExists('image_visible', $data ?? [], null);
        $this->setIfExists('salutation_visible', $data ?? [], null);
        $this->setIfExists('title_visible', $data ?? [], null);
        $this->setIfExists('visible_for_others', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets appointment_visible
     *
     * @return bool|null
     */
    public function getAppointmentVisible()
    {
        return $this->container['appointment_visible'];
    }

    /**
     * Sets appointment_visible
     *
     * @param bool|null $appointment_visible appointment_visible
     *
     * @return self
     */
    public function setAppointmentVisible($appointment_visible)
    {
        if (is_null($appointment_visible)) {
            throw new \InvalidArgumentException('non-nullable appointment_visible cannot be null');
        }
        $this->container['appointment_visible'] = $appointment_visible;

        return $this;
    }

    /**
     * Gets chat_visible
     *
     * @return bool|null
     */
    public function getChatVisible()
    {
        return $this->container['chat_visible'];
    }

    /**
     * Sets chat_visible
     *
     * @param bool|null $chat_visible handles reactions allowed
     *
     * @return self
     */
    public function setChatVisible($chat_visible)
    {
        if (is_null($chat_visible)) {
            throw new \InvalidArgumentException('non-nullable chat_visible cannot be null');
        }
        $this->container['chat_visible'] = $chat_visible;

        return $this;
    }

    /**
     * Gets email_visible
     *
     * @return bool|null
     */
    public function getEmailVisible()
    {
        return $this->container['email_visible'];
    }

    /**
     * Sets email_visible
     *
     * @param bool|null $email_visible email_visible
     *
     * @return self
     */
    public function setEmailVisible($email_visible)
    {
        if (is_null($email_visible)) {
            throw new \InvalidArgumentException('non-nullable email_visible cannot be null');
        }
        $this->container['email_visible'] = $email_visible;

        return $this;
    }

    /**
     * Gets image_visible
     *
     * @return bool|null
     */
    public function getImageVisible()
    {
        return $this->container['image_visible'];
    }

    /**
     * Sets image_visible
     *
     * @param bool|null $image_visible image_visible
     *
     * @return self
     */
    public function setImageVisible($image_visible)
    {
        if (is_null($image_visible)) {
            throw new \InvalidArgumentException('non-nullable image_visible cannot be null');
        }
        $this->container['image_visible'] = $image_visible;

        return $this;
    }

    /**
     * Gets salutation_visible
     *
     * @return bool|null
     */
    public function getSalutationVisible()
    {
        return $this->container['salutation_visible'];
    }

    /**
     * Sets salutation_visible
     *
     * @param bool|null $salutation_visible salutation_visible
     *
     * @return self
     */
    public function setSalutationVisible($salutation_visible)
    {
        if (is_null($salutation_visible)) {
            throw new \InvalidArgumentException('non-nullable salutation_visible cannot be null');
        }
        $this->container['salutation_visible'] = $salutation_visible;

        return $this;
    }

    /**
     * Gets title_visible
     *
     * @return bool|null
     */
    public function getTitleVisible()
    {
        return $this->container['title_visible'];
    }

    /**
     * Sets title_visible
     *
     * @param bool|null $title_visible title_visible
     *
     * @return self
     */
    public function setTitleVisible($title_visible)
    {
        if (is_null($title_visible)) {
            throw new \InvalidArgumentException('non-nullable title_visible cannot be null');
        }
        $this->container['title_visible'] = $title_visible;

        return $this;
    }

    /**
     * Gets visible_for_others
     *
     * @return bool|null
     */
    public function getVisibleForOthers()
    {
        return $this->container['visible_for_others'];
    }

    /**
     * Sets visible_for_others
     *
     * @param bool|null $visible_for_others visible_for_others
     *
     * @return self
     */
    public function setVisibleForOthers($visible_for_others)
    {
        if (is_null($visible_for_others)) {
            throw new \InvalidArgumentException('non-nullable visible_for_others cannot be null');
        }
        $this->container['visible_for_others'] = $visible_for_others;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


