<?php
/**
 * ConfigurationPatchChatRequestAdmin
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should be careful to interpreted them as html to avoid against xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.3.0-pre.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConfigurationPatchChatRequestAdmin Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigurationPatchChatRequestAdmin implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'configuration.PatchChatRequestAdmin';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'allow_links' => 'bool',
        'disabled_public_chat' => 'bool',
        'domain_filter' => '\OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminDomainFilter',
        'enabled' => 'bool',
        'image_moderation' => '\OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminImageModeration',
        'own_channels' => 'bool',
        'profanity_filter' => '\OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminProfanityFilter',
        'profanity_triggered_moderation' => '\OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminProfanityTriggeredModeration'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'allow_links' => null,
        'disabled_public_chat' => 'optional',
        'domain_filter' => null,
        'enabled' => null,
        'image_moderation' => null,
        'own_channels' => null,
        'profanity_filter' => null,
        'profanity_triggered_moderation' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'allow_links' => true,
        'disabled_public_chat' => false,
        'domain_filter' => true,
        'enabled' => false,
        'image_moderation' => true,
        'own_channels' => false,
        'profanity_filter' => true,
        'profanity_triggered_moderation' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allow_links' => 'allowLinks',
        'disabled_public_chat' => 'disabledPublicChat',
        'domain_filter' => 'domainFilter',
        'enabled' => 'enabled',
        'image_moderation' => 'imageModeration',
        'own_channels' => 'ownChannels',
        'profanity_filter' => 'profanityFilter',
        'profanity_triggered_moderation' => 'profanityTriggeredModeration'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allow_links' => 'setAllowLinks',
        'disabled_public_chat' => 'setDisabledPublicChat',
        'domain_filter' => 'setDomainFilter',
        'enabled' => 'setEnabled',
        'image_moderation' => 'setImageModeration',
        'own_channels' => 'setOwnChannels',
        'profanity_filter' => 'setProfanityFilter',
        'profanity_triggered_moderation' => 'setProfanityTriggeredModeration'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allow_links' => 'getAllowLinks',
        'disabled_public_chat' => 'getDisabledPublicChat',
        'domain_filter' => 'getDomainFilter',
        'enabled' => 'getEnabled',
        'image_moderation' => 'getImageModeration',
        'own_channels' => 'getOwnChannels',
        'profanity_filter' => 'getProfanityFilter',
        'profanity_triggered_moderation' => 'getProfanityTriggeredModeration'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('allow_links', $data ?? [], null);
        $this->setIfExists('disabled_public_chat', $data ?? [], null);
        $this->setIfExists('domain_filter', $data ?? [], null);
        $this->setIfExists('enabled', $data ?? [], null);
        $this->setIfExists('image_moderation', $data ?? [], null);
        $this->setIfExists('own_channels', $data ?? [], null);
        $this->setIfExists('profanity_filter', $data ?? [], null);
        $this->setIfExists('profanity_triggered_moderation', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allow_links
     *
     * @return bool|null
     */
    public function getAllowLinks()
    {
        return $this->container['allow_links'];
    }

    /**
     * Sets allow_links
     *
     * @param bool|null $allow_links allow_links
     *
     * @return self
     */
    public function setAllowLinks($allow_links)
    {
        if (is_null($allow_links)) {
            array_push($this->openAPINullablesSetToNull, 'allow_links');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allow_links', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allow_links'] = $allow_links;

        return $this;
    }

    /**
     * Gets disabled_public_chat
     *
     * @return bool|null
     */
    public function getDisabledPublicChat()
    {
        return $this->container['disabled_public_chat'];
    }

    /**
     * Sets disabled_public_chat
     *
     * @param bool|null $disabled_public_chat disabled_public_chat
     *
     * @return self
     */
    public function setDisabledPublicChat($disabled_public_chat)
    {
        if (is_null($disabled_public_chat)) {
            throw new \InvalidArgumentException('non-nullable disabled_public_chat cannot be null');
        }
        $this->container['disabled_public_chat'] = $disabled_public_chat;

        return $this;
    }

    /**
     * Gets domain_filter
     *
     * @return \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminDomainFilter|null
     */
    public function getDomainFilter()
    {
        return $this->container['domain_filter'];
    }

    /**
     * Sets domain_filter
     *
     * @param \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminDomainFilter|null $domain_filter domain_filter
     *
     * @return self
     */
    public function setDomainFilter($domain_filter)
    {
        if (is_null($domain_filter)) {
            array_push($this->openAPINullablesSetToNull, 'domain_filter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domain_filter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domain_filter'] = $domain_filter;

        return $this;
    }

    /**
     * Gets enabled
     *
     * @return bool|null
     */
    public function getEnabled()
    {
        return $this->container['enabled'];
    }

    /**
     * Sets enabled
     *
     * @param bool|null $enabled enabled
     *
     * @return self
     */
    public function setEnabled($enabled)
    {
        if (is_null($enabled)) {
            throw new \InvalidArgumentException('non-nullable enabled cannot be null');
        }
        $this->container['enabled'] = $enabled;

        return $this;
    }

    /**
     * Gets image_moderation
     *
     * @return \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminImageModeration|null
     */
    public function getImageModeration()
    {
        return $this->container['image_moderation'];
    }

    /**
     * Sets image_moderation
     *
     * @param \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminImageModeration|null $image_moderation image_moderation
     *
     * @return self
     */
    public function setImageModeration($image_moderation)
    {
        if (is_null($image_moderation)) {
            array_push($this->openAPINullablesSetToNull, 'image_moderation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_moderation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_moderation'] = $image_moderation;

        return $this;
    }

    /**
     * Gets own_channels
     *
     * @return bool|null
     */
    public function getOwnChannels()
    {
        return $this->container['own_channels'];
    }

    /**
     * Sets own_channels
     *
     * @param bool|null $own_channels can be set but will have no effect if chat is disabled
     *
     * @return self
     */
    public function setOwnChannels($own_channels)
    {
        if (is_null($own_channels)) {
            throw new \InvalidArgumentException('non-nullable own_channels cannot be null');
        }
        $this->container['own_channels'] = $own_channels;

        return $this;
    }

    /**
     * Gets profanity_filter
     *
     * @return \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminProfanityFilter|null
     */
    public function getProfanityFilter()
    {
        return $this->container['profanity_filter'];
    }

    /**
     * Sets profanity_filter
     *
     * @param \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminProfanityFilter|null $profanity_filter profanity_filter
     *
     * @return self
     */
    public function setProfanityFilter($profanity_filter)
    {
        if (is_null($profanity_filter)) {
            array_push($this->openAPINullablesSetToNull, 'profanity_filter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('profanity_filter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['profanity_filter'] = $profanity_filter;

        return $this;
    }

    /**
     * Gets profanity_triggered_moderation
     *
     * @return \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminProfanityTriggeredModeration|null
     */
    public function getProfanityTriggeredModeration()
    {
        return $this->container['profanity_triggered_moderation'];
    }

    /**
     * Sets profanity_triggered_moderation
     *
     * @param \OpenAPI\Client\Model\ConfigurationPatchChatRequestAdminProfanityTriggeredModeration|null $profanity_triggered_moderation profanity_triggered_moderation
     *
     * @return self
     */
    public function setProfanityTriggeredModeration($profanity_triggered_moderation)
    {
        if (is_null($profanity_triggered_moderation)) {
            array_push($this->openAPINullablesSetToNull, 'profanity_triggered_moderation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('profanity_triggered_moderation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['profanity_triggered_moderation'] = $profanity_triggered_moderation;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


