<?php
/**
 * ConfigurationDesignRequestAdmin
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should be careful to interpreted them as html to avoid against xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.5.0-pre
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConfigurationDesignRequestAdmin Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConfigurationDesignRequestAdmin implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'configuration.DesignRequestAdmin';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'background_dark_primary' => 'string',
        'background_dark_primary_auto' => 'bool',
        'background_dark_secondary' => 'string',
        'background_dark_secondary_auto' => 'bool',
        'background_light_primary' => 'string',
        'background_light_secondary' => 'string',
        'background_type' => 'string',
        'company_logo' => 'string',
        'scheme_current' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'background_dark_primary' => null,
        'background_dark_primary_auto' => null,
        'background_dark_secondary' => null,
        'background_dark_secondary_auto' => null,
        'background_light_primary' => null,
        'background_light_secondary' => null,
        'background_type' => null,
        'company_logo' => null,
        'scheme_current' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'background_dark_primary' => false,
        'background_dark_primary_auto' => false,
        'background_dark_secondary' => false,
        'background_dark_secondary_auto' => false,
        'background_light_primary' => false,
        'background_light_secondary' => false,
        'background_type' => false,
        'company_logo' => true,
        'scheme_current' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'background_dark_primary' => 'backgroundDarkPrimary',
        'background_dark_primary_auto' => 'backgroundDarkPrimaryAuto',
        'background_dark_secondary' => 'backgroundDarkSecondary',
        'background_dark_secondary_auto' => 'backgroundDarkSecondaryAuto',
        'background_light_primary' => 'backgroundLightPrimary',
        'background_light_secondary' => 'backgroundLightSecondary',
        'background_type' => 'backgroundType',
        'company_logo' => 'companyLogo',
        'scheme_current' => 'schemeCurrent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'background_dark_primary' => 'setBackgroundDarkPrimary',
        'background_dark_primary_auto' => 'setBackgroundDarkPrimaryAuto',
        'background_dark_secondary' => 'setBackgroundDarkSecondary',
        'background_dark_secondary_auto' => 'setBackgroundDarkSecondaryAuto',
        'background_light_primary' => 'setBackgroundLightPrimary',
        'background_light_secondary' => 'setBackgroundLightSecondary',
        'background_type' => 'setBackgroundType',
        'company_logo' => 'setCompanyLogo',
        'scheme_current' => 'setSchemeCurrent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'background_dark_primary' => 'getBackgroundDarkPrimary',
        'background_dark_primary_auto' => 'getBackgroundDarkPrimaryAuto',
        'background_dark_secondary' => 'getBackgroundDarkSecondary',
        'background_dark_secondary_auto' => 'getBackgroundDarkSecondaryAuto',
        'background_light_primary' => 'getBackgroundLightPrimary',
        'background_light_secondary' => 'getBackgroundLightSecondary',
        'background_type' => 'getBackgroundType',
        'company_logo' => 'getCompanyLogo',
        'scheme_current' => 'getSchemeCurrent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const BACKGROUND_TYPE_GRADIENT = 'Gradient';
    public const BACKGROUND_TYPE_COLOR = 'Color';
    public const BACKGROUND_TYPE_TRANSPARENT = 'Transparent';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getBackgroundTypeAllowableValues()
    {
        return [
            self::BACKGROUND_TYPE_GRADIENT,
            self::BACKGROUND_TYPE_COLOR,
            self::BACKGROUND_TYPE_TRANSPARENT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('background_dark_primary', $data ?? [], null);
        $this->setIfExists('background_dark_primary_auto', $data ?? [], null);
        $this->setIfExists('background_dark_secondary', $data ?? [], null);
        $this->setIfExists('background_dark_secondary_auto', $data ?? [], null);
        $this->setIfExists('background_light_primary', $data ?? [], null);
        $this->setIfExists('background_light_secondary', $data ?? [], null);
        $this->setIfExists('background_type', $data ?? [], null);
        $this->setIfExists('company_logo', $data ?? [], null);
        $this->setIfExists('scheme_current', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getBackgroundTypeAllowableValues();
        if (!is_null($this->container['background_type']) && !in_array($this->container['background_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'background_type', must be one of '%s'",
                $this->container['background_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets background_dark_primary
     *
     * @return string|null
     */
    public function getBackgroundDarkPrimary()
    {
        return $this->container['background_dark_primary'];
    }

    /**
     * Sets background_dark_primary
     *
     * @param string|null $background_dark_primary only used for backgroundType{Gradient|Color}; hexcolor or enum: `\"backgroundPrimary\"` `\"backgroundSecondary\"` `\"backgroundTertiary\"` `\"border\"` `\"contrast\"` `\"error\"` `\"primary\"` `\"secondary\"` `\"success\"` `\"textPrimary\"` `\"textSecondary\"`
     *
     * @return self
     */
    public function setBackgroundDarkPrimary($background_dark_primary)
    {
        if (is_null($background_dark_primary)) {
            throw new \InvalidArgumentException('non-nullable background_dark_primary cannot be null');
        }
        $this->container['background_dark_primary'] = $background_dark_primary;

        return $this;
    }

    /**
     * Gets background_dark_primary_auto
     *
     * @return bool|null
     */
    public function getBackgroundDarkPrimaryAuto()
    {
        return $this->container['background_dark_primary_auto'];
    }

    /**
     * Sets background_dark_primary_auto
     *
     * @param bool|null $background_dark_primary_auto only used for backgroundType{Gradient|Color}
     *
     * @return self
     */
    public function setBackgroundDarkPrimaryAuto($background_dark_primary_auto)
    {
        if (is_null($background_dark_primary_auto)) {
            throw new \InvalidArgumentException('non-nullable background_dark_primary_auto cannot be null');
        }
        $this->container['background_dark_primary_auto'] = $background_dark_primary_auto;

        return $this;
    }

    /**
     * Gets background_dark_secondary
     *
     * @return string|null
     */
    public function getBackgroundDarkSecondary()
    {
        return $this->container['background_dark_secondary'];
    }

    /**
     * Sets background_dark_secondary
     *
     * @param string|null $background_dark_secondary only used for backgroundType{Gradient}; hexcolor or enum: `\"backgroundPrimary\"` `\"backgroundSecondary\"` `\"backgroundTertiary\"` `\"border\"` `\"contrast\"` `\"error\"` `\"primary\"` `\"secondary\"` `\"success\"` `\"textPrimary\"` `\"textSecondary\"`
     *
     * @return self
     */
    public function setBackgroundDarkSecondary($background_dark_secondary)
    {
        if (is_null($background_dark_secondary)) {
            throw new \InvalidArgumentException('non-nullable background_dark_secondary cannot be null');
        }
        $this->container['background_dark_secondary'] = $background_dark_secondary;

        return $this;
    }

    /**
     * Gets background_dark_secondary_auto
     *
     * @return bool|null
     */
    public function getBackgroundDarkSecondaryAuto()
    {
        return $this->container['background_dark_secondary_auto'];
    }

    /**
     * Sets background_dark_secondary_auto
     *
     * @param bool|null $background_dark_secondary_auto only used for backgroundType{Gradient}
     *
     * @return self
     */
    public function setBackgroundDarkSecondaryAuto($background_dark_secondary_auto)
    {
        if (is_null($background_dark_secondary_auto)) {
            throw new \InvalidArgumentException('non-nullable background_dark_secondary_auto cannot be null');
        }
        $this->container['background_dark_secondary_auto'] = $background_dark_secondary_auto;

        return $this;
    }

    /**
     * Gets background_light_primary
     *
     * @return string|null
     */
    public function getBackgroundLightPrimary()
    {
        return $this->container['background_light_primary'];
    }

    /**
     * Sets background_light_primary
     *
     * @param string|null $background_light_primary only used for backgroundType{Gradient|Color}; hexcolor or enum: `\"backgroundPrimary\"` `\"backgroundSecondary\"` `\"backgroundTertiary\"` `\"border\"` `\"contrast\"` `\"error\"` `\"primary\"` `\"secondary\"` `\"success\"` `\"textPrimary\"` `\"textSecondary\"`
     *
     * @return self
     */
    public function setBackgroundLightPrimary($background_light_primary)
    {
        if (is_null($background_light_primary)) {
            throw new \InvalidArgumentException('non-nullable background_light_primary cannot be null');
        }
        $this->container['background_light_primary'] = $background_light_primary;

        return $this;
    }

    /**
     * Gets background_light_secondary
     *
     * @return string|null
     */
    public function getBackgroundLightSecondary()
    {
        return $this->container['background_light_secondary'];
    }

    /**
     * Sets background_light_secondary
     *
     * @param string|null $background_light_secondary only used for backgroundType{Gradient}; hexcolor or enum: `\"backgroundPrimary\"` `\"backgroundSecondary\"` `\"backgroundTertiary\"` `\"border\"` `\"contrast\"` `\"error\"` `\"primary\"` `\"secondary\"` `\"success\"` `\"textPrimary\"` `\"textSecondary\"`
     *
     * @return self
     */
    public function setBackgroundLightSecondary($background_light_secondary)
    {
        if (is_null($background_light_secondary)) {
            throw new \InvalidArgumentException('non-nullable background_light_secondary cannot be null');
        }
        $this->container['background_light_secondary'] = $background_light_secondary;

        return $this;
    }

    /**
     * Gets background_type
     *
     * @return string|null
     */
    public function getBackgroundType()
    {
        return $this->container['background_type'];
    }

    /**
     * Sets background_type
     *
     * @param string|null $background_type background_type
     *
     * @return self
     */
    public function setBackgroundType($background_type)
    {
        if (is_null($background_type)) {
            throw new \InvalidArgumentException('non-nullable background_type cannot be null');
        }
        $allowedValues = $this->getBackgroundTypeAllowableValues();
        if (!in_array($background_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'background_type', must be one of '%s'",
                    $background_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['background_type'] = $background_type;

        return $this;
    }

    /**
     * Gets company_logo
     *
     * @return string|null
     */
    public function getCompanyLogo()
    {
        return $this->container['company_logo'];
    }

    /**
     * Sets company_logo
     *
     * @param string|null $company_logo media id
     *
     * @return self
     */
    public function setCompanyLogo($company_logo)
    {
        if (is_null($company_logo)) {
            array_push($this->openAPINullablesSetToNull, 'company_logo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('company_logo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['company_logo'] = $company_logo;

        return $this;
    }

    /**
     * Gets scheme_current
     *
     * @return string|null
     */
    public function getSchemeCurrent()
    {
        return $this->container['scheme_current'];
    }

    /**
     * Sets scheme_current
     *
     * @param string|null $scheme_current scheme id
     *
     * @return self
     */
    public function setSchemeCurrent($scheme_current)
    {
        if (is_null($scheme_current)) {
            throw new \InvalidArgumentException('non-nullable scheme_current cannot be null');
        }
        $this->container['scheme_current'] = $scheme_current;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


