<?php
/**
 * ContentEntryPostRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should not be interpreted as html to avoid unexpected bahavior, like xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.5.2
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.20.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ContentEntryPostRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ContentEntryPostRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'content.EntryPostRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'access' => '\OpenAPI\Client\Model\ModelAccess',
        'booking_enabled' => 'bool',
        'data_set' => 'array<string,\OpenAPI\Client\Model\ContentEntryValueRequest>',
        'end' => 'int',
        'external_id' => 'string',
        'external_party' => 'string',
        'id' => 'string',
        'keyword_ids' => 'string[]',
        'parent_id' => 'string',
        'position' => 'int',
        'published_at' => 'int',
        'start' => 'int',
        'tabs' => '\OpenAPI\Client\Model\ContentEntryTabRequest[]',
        'time_zone' => 'string',
        'title' => 'string',
        'widgets' => 'array<string,\OpenAPI\Client\Model\ContentbuilderRequestItem>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'access' => null,
        'booking_enabled' => 'optional',
        'data_set' => null,
        'end' => null,
        'external_id' => 'optional',
        'external_party' => 'optional',
        'id' => null,
        'keyword_ids' => null,
        'parent_id' => null,
        'position' => null,
        'published_at' => null,
        'start' => null,
        'tabs' => null,
        'time_zone' => null,
        'title' => null,
        'widgets' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'access' => false,
        'booking_enabled' => false,
        'data_set' => false,
        'end' => false,
        'external_id' => true,
        'external_party' => true,
        'id' => false,
        'keyword_ids' => false,
        'parent_id' => true,
        'position' => false,
        'published_at' => true,
        'start' => false,
        'tabs' => false,
        'time_zone' => false,
        'title' => false,
        'widgets' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'access' => 'access',
        'booking_enabled' => 'bookingEnabled',
        'data_set' => 'dataSet',
        'end' => 'end',
        'external_id' => 'externalId',
        'external_party' => 'externalParty',
        'id' => 'id',
        'keyword_ids' => 'keywordIds',
        'parent_id' => 'parentId',
        'position' => 'position',
        'published_at' => 'publishedAt',
        'start' => 'start',
        'tabs' => 'tabs',
        'time_zone' => 'timeZone',
        'title' => 'title',
        'widgets' => 'widgets'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'access' => 'setAccess',
        'booking_enabled' => 'setBookingEnabled',
        'data_set' => 'setDataSet',
        'end' => 'setEnd',
        'external_id' => 'setExternalId',
        'external_party' => 'setExternalParty',
        'id' => 'setId',
        'keyword_ids' => 'setKeywordIds',
        'parent_id' => 'setParentId',
        'position' => 'setPosition',
        'published_at' => 'setPublishedAt',
        'start' => 'setStart',
        'tabs' => 'setTabs',
        'time_zone' => 'setTimeZone',
        'title' => 'setTitle',
        'widgets' => 'setWidgets'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'access' => 'getAccess',
        'booking_enabled' => 'getBookingEnabled',
        'data_set' => 'getDataSet',
        'end' => 'getEnd',
        'external_id' => 'getExternalId',
        'external_party' => 'getExternalParty',
        'id' => 'getId',
        'keyword_ids' => 'getKeywordIds',
        'parent_id' => 'getParentId',
        'position' => 'getPosition',
        'published_at' => 'getPublishedAt',
        'start' => 'getStart',
        'tabs' => 'getTabs',
        'time_zone' => 'getTimeZone',
        'title' => 'getTitle',
        'widgets' => 'getWidgets'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const EXTERNAL_PARTY_DOO = 'Doo';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExternalPartyAllowableValues()
    {
        return [
            self::EXTERNAL_PARTY_DOO,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('access', $data ?? [], null);
        $this->setIfExists('booking_enabled', $data ?? [], null);
        $this->setIfExists('data_set', $data ?? [], null);
        $this->setIfExists('end', $data ?? [], null);
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('external_party', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('keyword_ids', $data ?? [], null);
        $this->setIfExists('parent_id', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('published_at', $data ?? [], null);
        $this->setIfExists('start', $data ?? [], null);
        $this->setIfExists('tabs', $data ?? [], null);
        $this->setIfExists('time_zone', $data ?? [], null);
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('widgets', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getExternalPartyAllowableValues();
        if (!is_null($this->container['external_party']) && !in_array($this->container['external_party'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'external_party', must be one of '%s'",
                $this->container['external_party'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets access
     *
     * @return \OpenAPI\Client\Model\ModelAccess|null
     */
    public function getAccess()
    {
        return $this->container['access'];
    }

    /**
     * Sets access
     *
     * @param \OpenAPI\Client\Model\ModelAccess|null $access access
     *
     * @return self
     */
    public function setAccess($access)
    {
        if (is_null($access)) {
            throw new \InvalidArgumentException('non-nullable access cannot be null');
        }
        $this->container['access'] = $access;

        return $this;
    }

    /**
     * Gets booking_enabled
     *
     * @return bool|null
     */
    public function getBookingEnabled()
    {
        return $this->container['booking_enabled'];
    }

    /**
     * Sets booking_enabled
     *
     * @param bool|null $booking_enabled bookingEnabled can only be true if externalId is not null; Default: `false`
     *
     * @return self
     */
    public function setBookingEnabled($booking_enabled)
    {
        if (is_null($booking_enabled)) {
            throw new \InvalidArgumentException('non-nullable booking_enabled cannot be null');
        }
        $this->container['booking_enabled'] = $booking_enabled;

        return $this;
    }

    /**
     * Gets data_set
     *
     * @return array<string,\OpenAPI\Client\Model\ContentEntryValueRequest>|null
     */
    public function getDataSet()
    {
        return $this->container['data_set'];
    }

    /**
     * Sets data_set
     *
     * @param array<string,\OpenAPI\Client\Model\ContentEntryValueRequest>|null $data_set data_set
     *
     * @return self
     */
    public function setDataSet($data_set)
    {
        if (is_null($data_set)) {
            throw new \InvalidArgumentException('non-nullable data_set cannot be null');
        }
        $this->container['data_set'] = $data_set;

        return $this;
    }

    /**
     * Gets end
     *
     * @return int|null
     */
    public function getEnd()
    {
        return $this->container['end'];
    }

    /**
     * Sets end
     *
     * @param int|null $end end
     *
     * @return self
     */
    public function setEnd($end)
    {
        if (is_null($end)) {
            throw new \InvalidArgumentException('non-nullable end cannot be null');
        }
        $this->container['end'] = $end;

        return $this;
    }

    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id externalParty must be set if externalId is set; Default: `null`
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            array_push($this->openAPINullablesSetToNull, 'external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets external_party
     *
     * @return string|null
     */
    public function getExternalParty()
    {
        return $this->container['external_party'];
    }

    /**
     * Sets external_party
     *
     * @param string|null $external_party Default: `null`
     *
     * @return self
     */
    public function setExternalParty($external_party)
    {
        if (is_null($external_party)) {
            array_push($this->openAPINullablesSetToNull, 'external_party');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_party', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getExternalPartyAllowableValues();
        if (!is_null($external_party) && !in_array($external_party, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'external_party', must be one of '%s'",
                    $external_party,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['external_party'] = $external_party;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets keyword_ids
     *
     * @return string[]|null
     */
    public function getKeywordIds()
    {
        return $this->container['keyword_ids'];
    }

    /**
     * Sets keyword_ids
     *
     * @param string[]|null $keyword_ids keyword_ids
     *
     * @return self
     */
    public function setKeywordIds($keyword_ids)
    {
        if (is_null($keyword_ids)) {
            throw new \InvalidArgumentException('non-nullable keyword_ids cannot be null');
        }
        $this->container['keyword_ids'] = $keyword_ids;

        return $this;
    }

    /**
     * Gets parent_id
     *
     * @return string|null
     */
    public function getParentId()
    {
        return $this->container['parent_id'];
    }

    /**
     * Sets parent_id
     *
     * @param string|null $parent_id parent_id
     *
     * @return self
     */
    public function setParentId($parent_id)
    {
        if (is_null($parent_id)) {
            array_push($this->openAPINullablesSetToNull, 'parent_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('parent_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['parent_id'] = $parent_id;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int|null $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            throw new \InvalidArgumentException('non-nullable position cannot be null');
        }
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets published_at
     *
     * @return int|null
     */
    public function getPublishedAt()
    {
        return $this->container['published_at'];
    }

    /**
     * Sets published_at
     *
     * @param int|null $published_at published_at
     *
     * @return self
     */
    public function setPublishedAt($published_at)
    {
        if (is_null($published_at)) {
            array_push($this->openAPINullablesSetToNull, 'published_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('published_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['published_at'] = $published_at;

        return $this;
    }

    /**
     * Gets start
     *
     * @return int|null
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param int|null $start start
     *
     * @return self
     */
    public function setStart($start)
    {
        if (is_null($start)) {
            throw new \InvalidArgumentException('non-nullable start cannot be null');
        }
        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets tabs
     *
     * @return \OpenAPI\Client\Model\ContentEntryTabRequest[]|null
     */
    public function getTabs()
    {
        return $this->container['tabs'];
    }

    /**
     * Sets tabs
     *
     * @param \OpenAPI\Client\Model\ContentEntryTabRequest[]|null $tabs tabs
     *
     * @return self
     */
    public function setTabs($tabs)
    {
        if (is_null($tabs)) {
            throw new \InvalidArgumentException('non-nullable tabs cannot be null');
        }
        $this->container['tabs'] = $tabs;

        return $this;
    }

    /**
     * Gets time_zone
     *
     * @return string|null
     */
    public function getTimeZone()
    {
        return $this->container['time_zone'];
    }

    /**
     * Sets time_zone
     *
     * @param string|null $time_zone IANA Time Zone
     *
     * @return self
     */
    public function setTimeZone($time_zone)
    {
        if (is_null($time_zone)) {
            throw new \InvalidArgumentException('non-nullable time_zone cannot be null');
        }
        $this->container['time_zone'] = $time_zone;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            throw new \InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets widgets
     *
     * @return array<string,\OpenAPI\Client\Model\ContentbuilderRequestItem>|null
     */
    public function getWidgets()
    {
        return $this->container['widgets'];
    }

    /**
     * Sets widgets
     *
     * @param array<string,\OpenAPI\Client\Model\ContentbuilderRequestItem>|null $widgets widgets
     *
     * @return self
     */
    public function setWidgets($widgets)
    {
        if (is_null($widgets)) {
            throw new \InvalidArgumentException('non-nullable widgets cannot be null');
        }
        $this->container['widgets'] = $widgets;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


