<?php
/**
 * GamificationruleCursorFilterOption
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should not be interpreted as html to avoid unexpected bahavior, like xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.11.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.24.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GamificationruleCursorFilterOption Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GamificationruleCursorFilterOption implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'gamificationrule.CursorFilterOption';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'actions' => 'string[]',
        'ids' => 'string[]',
        'leaderboard_ids' => 'string[]',
        'object_ids' => 'string[]',
        'object_types' => 'string[]',
        'project_ids' => 'string[]',
        'reference_ids' => 'string[]',
        'repetitions' => 'int[]',
        'values' => 'int[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'actions' => 'optional',
        'ids' => 'optional',
        'leaderboard_ids' => 'optional',
        'object_ids' => 'optional',
        'object_types' => 'optional',
        'project_ids' => 'optional',
        'reference_ids' => 'optional',
        'repetitions' => 'optional',
        'values' => 'optional'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'actions' => false,
        'ids' => false,
        'leaderboard_ids' => false,
        'object_ids' => false,
        'object_types' => false,
        'project_ids' => false,
        'reference_ids' => false,
        'repetitions' => false,
        'values' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'actions' => 'actions',
        'ids' => 'ids',
        'leaderboard_ids' => 'leaderboardIds',
        'object_ids' => 'objectIds',
        'object_types' => 'objectTypes',
        'project_ids' => 'projectIds',
        'reference_ids' => 'referenceIds',
        'repetitions' => 'repetitions',
        'values' => 'values'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'actions' => 'setActions',
        'ids' => 'setIds',
        'leaderboard_ids' => 'setLeaderboardIds',
        'object_ids' => 'setObjectIds',
        'object_types' => 'setObjectTypes',
        'project_ids' => 'setProjectIds',
        'reference_ids' => 'setReferenceIds',
        'repetitions' => 'setRepetitions',
        'values' => 'setValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'actions' => 'getActions',
        'ids' => 'getIds',
        'leaderboard_ids' => 'getLeaderboardIds',
        'object_ids' => 'getObjectIds',
        'object_types' => 'getObjectTypes',
        'project_ids' => 'getProjectIds',
        'reference_ids' => 'getReferenceIds',
        'repetitions' => 'getRepetitions',
        'values' => 'getValues'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const ACTIONS_CREATE = 'Create';
    public const ACTIONS_DELETE = 'Delete';
    public const ACTIONS_VIEWED = 'Viewed';
    public const OBJECT_TYPES_CALENDAR = 'Calendar';
    public const OBJECT_TYPES_CALENDAR_ENTRY = 'CalendarEntry';
    public const OBJECT_TYPES_CALENDAR_ENTRY_RATING = 'CalendarEntryRating';
    public const OBJECT_TYPES_CHAT_FEED = 'ChatFeed';
    public const OBJECT_TYPES_CHAT_FEED_MESSAGE_FILE_IMAGE = 'ChatFeedMessageFileImage';
    public const OBJECT_TYPES_CHAT_FEED_MESSAGE_REACTION_LIKE = 'ChatFeedMessageReactionLike';
    public const OBJECT_TYPES_CHAT_FEED_MESSAGE_TEXT = 'ChatFeedMessageText';
    public const OBJECT_TYPES_DIRECTORY = 'Directory';
    public const OBJECT_TYPES_DIRECTORY_CONTENT_ROW = 'DirectoryContentRow';
    public const OBJECT_TYPES_JOURNEY = 'Journey';
    public const OBJECT_TYPES_LINK = 'Link';
    public const OBJECT_TYPES_LOCATION = 'Location';
    public const OBJECT_TYPES_LOCATION_MAP = 'LocationMap';
    public const OBJECT_TYPES_MEDIA_AUDIO = 'MediaAudio';
    public const OBJECT_TYPES_MEDIA_DOCUMENT = 'MediaDocument';
    public const OBJECT_TYPES_MEDIA_FOLDER = 'MediaFolder';
    public const OBJECT_TYPES_MEDIA_IMAGE = 'MediaImage';
    public const OBJECT_TYPES_MEDIA_VIDEO = 'MediaVideo';
    public const OBJECT_TYPES_MEDIA_OTHER = 'MediaOther';
    public const OBJECT_TYPES_NEWS = 'News';
    public const OBJECT_TYPES_NOTIFICATION_CENTER = 'NotificationCenter';
    public const OBJECT_TYPES_PAGE = 'Page';
    public const OBJECT_TYPES_PROJECT = 'Project';
    public const OBJECT_TYPES_PUSH_ENTRY = 'PushEntry';
    public const OBJECT_TYPES_STREAM = 'Stream';
    public const OBJECT_TYPES_SURVEY = 'Survey';
    public const OBJECT_TYPES_SURVEY_PARTICIPATION = 'SurveyParticipation';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getActionsAllowableValues()
    {
        return [
            self::ACTIONS_CREATE,
            self::ACTIONS_DELETE,
            self::ACTIONS_VIEWED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjectTypesAllowableValues()
    {
        return [
            self::OBJECT_TYPES_CALENDAR,
            self::OBJECT_TYPES_CALENDAR_ENTRY,
            self::OBJECT_TYPES_CALENDAR_ENTRY_RATING,
            self::OBJECT_TYPES_CHAT_FEED,
            self::OBJECT_TYPES_CHAT_FEED_MESSAGE_FILE_IMAGE,
            self::OBJECT_TYPES_CHAT_FEED_MESSAGE_REACTION_LIKE,
            self::OBJECT_TYPES_CHAT_FEED_MESSAGE_TEXT,
            self::OBJECT_TYPES_DIRECTORY,
            self::OBJECT_TYPES_DIRECTORY_CONTENT_ROW,
            self::OBJECT_TYPES_JOURNEY,
            self::OBJECT_TYPES_LINK,
            self::OBJECT_TYPES_LOCATION,
            self::OBJECT_TYPES_LOCATION_MAP,
            self::OBJECT_TYPES_MEDIA_AUDIO,
            self::OBJECT_TYPES_MEDIA_DOCUMENT,
            self::OBJECT_TYPES_MEDIA_FOLDER,
            self::OBJECT_TYPES_MEDIA_IMAGE,
            self::OBJECT_TYPES_MEDIA_VIDEO,
            self::OBJECT_TYPES_MEDIA_OTHER,
            self::OBJECT_TYPES_NEWS,
            self::OBJECT_TYPES_NOTIFICATION_CENTER,
            self::OBJECT_TYPES_PAGE,
            self::OBJECT_TYPES_PROJECT,
            self::OBJECT_TYPES_PUSH_ENTRY,
            self::OBJECT_TYPES_STREAM,
            self::OBJECT_TYPES_SURVEY,
            self::OBJECT_TYPES_SURVEY_PARTICIPATION,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('actions', $data ?? [], null);
        $this->setIfExists('ids', $data ?? [], null);
        $this->setIfExists('leaderboard_ids', $data ?? [], null);
        $this->setIfExists('object_ids', $data ?? [], null);
        $this->setIfExists('object_types', $data ?? [], null);
        $this->setIfExists('project_ids', $data ?? [], null);
        $this->setIfExists('reference_ids', $data ?? [], null);
        $this->setIfExists('repetitions', $data ?? [], null);
        $this->setIfExists('values', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets actions
     *
     * @return string[]|null
     */
    public function getActions()
    {
        return $this->container['actions'];
    }

    /**
     * Sets actions
     *
     * @param string[]|null $actions actions
     *
     * @return self
     */
    public function setActions($actions)
    {
        if (is_null($actions)) {
            throw new \InvalidArgumentException('non-nullable actions cannot be null');
        }
        $allowedValues = $this->getActionsAllowableValues();
        if (array_diff($actions, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'actions', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['actions'] = $actions;

        return $this;
    }

    /**
     * Gets ids
     *
     * @return string[]|null
     */
    public function getIds()
    {
        return $this->container['ids'];
    }

    /**
     * Sets ids
     *
     * @param string[]|null $ids ids
     *
     * @return self
     */
    public function setIds($ids)
    {
        if (is_null($ids)) {
            throw new \InvalidArgumentException('non-nullable ids cannot be null');
        }
        $this->container['ids'] = $ids;

        return $this;
    }

    /**
     * Gets leaderboard_ids
     *
     * @return string[]|null
     */
    public function getLeaderboardIds()
    {
        return $this->container['leaderboard_ids'];
    }

    /**
     * Sets leaderboard_ids
     *
     * @param string[]|null $leaderboard_ids leaderboard_ids
     *
     * @return self
     */
    public function setLeaderboardIds($leaderboard_ids)
    {
        if (is_null($leaderboard_ids)) {
            throw new \InvalidArgumentException('non-nullable leaderboard_ids cannot be null');
        }
        $this->container['leaderboard_ids'] = $leaderboard_ids;

        return $this;
    }

    /**
     * Gets object_ids
     *
     * @return string[]|null
     */
    public function getObjectIds()
    {
        return $this->container['object_ids'];
    }

    /**
     * Sets object_ids
     *
     * @param string[]|null $object_ids object_ids
     *
     * @return self
     */
    public function setObjectIds($object_ids)
    {
        if (is_null($object_ids)) {
            throw new \InvalidArgumentException('non-nullable object_ids cannot be null');
        }
        $this->container['object_ids'] = $object_ids;

        return $this;
    }

    /**
     * Gets object_types
     *
     * @return string[]|null
     */
    public function getObjectTypes()
    {
        return $this->container['object_types'];
    }

    /**
     * Sets object_types
     *
     * @param string[]|null $object_types object_types
     *
     * @return self
     */
    public function setObjectTypes($object_types)
    {
        if (is_null($object_types)) {
            throw new \InvalidArgumentException('non-nullable object_types cannot be null');
        }
        $allowedValues = $this->getObjectTypesAllowableValues();
        if (array_diff($object_types, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'object_types', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['object_types'] = $object_types;

        return $this;
    }

    /**
     * Gets project_ids
     *
     * @return string[]|null
     */
    public function getProjectIds()
    {
        return $this->container['project_ids'];
    }

    /**
     * Sets project_ids
     *
     * @param string[]|null $project_ids project_ids
     *
     * @return self
     */
    public function setProjectIds($project_ids)
    {
        if (is_null($project_ids)) {
            throw new \InvalidArgumentException('non-nullable project_ids cannot be null');
        }
        $this->container['project_ids'] = $project_ids;

        return $this;
    }

    /**
     * Gets reference_ids
     *
     * @return string[]|null
     */
    public function getReferenceIds()
    {
        return $this->container['reference_ids'];
    }

    /**
     * Sets reference_ids
     *
     * @param string[]|null $reference_ids reference_ids
     *
     * @return self
     */
    public function setReferenceIds($reference_ids)
    {
        if (is_null($reference_ids)) {
            throw new \InvalidArgumentException('non-nullable reference_ids cannot be null');
        }
        $this->container['reference_ids'] = $reference_ids;

        return $this;
    }

    /**
     * Gets repetitions
     *
     * @return int[]|null
     */
    public function getRepetitions()
    {
        return $this->container['repetitions'];
    }

    /**
     * Sets repetitions
     *
     * @param int[]|null $repetitions repetitions
     *
     * @return self
     */
    public function setRepetitions($repetitions)
    {
        if (is_null($repetitions)) {
            throw new \InvalidArgumentException('non-nullable repetitions cannot be null');
        }
        $this->container['repetitions'] = $repetitions;

        return $this;
    }

    /**
     * Gets values
     *
     * @return int[]|null
     */
    public function getValues()
    {
        return $this->container['values'];
    }

    /**
     * Sets values
     *
     * @param int[]|null $values values
     *
     * @return self
     */
    public function setValues($values)
    {
        if (is_null($values)) {
            throw new \InvalidArgumentException('non-nullable values cannot be null');
        }
        $this->container['values'] = $values;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


