<?php
/**
 * ModelDirectoryItem
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should be careful to interpreted them as html to avoid against xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.3.0-pre.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ModelDirectoryItem Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelDirectoryItem implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'model.DirectoryItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'allow_multiple' => 'int',
        'auto_play' => 'bool',
        'creator_name_pattern' => 'string',
        'date_time_format' => 'string',
        'download' => 'bool',
        'filter' => '\OpenAPI\Client\Model\ModelSearch',
        'icon' => 'string',
        'id' => 'string',
        'link_behavior' => 'string',
        'localization' => 'array<string,\OpenAPI\Client\Model\ModelDirectoryItemLocalization>',
        'readonly' => 'bool',
        'reference' => 'string',
        'reference_id' => 'string',
        'required' => 'bool',
        'show_map' => 'bool',
        'show_title' => 'bool',
        'sub_type' => 'string',
        'type' => 'string',
        'zoom_level' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'allow_multiple' => null,
        'auto_play' => null,
        'creator_name_pattern' => null,
        'date_time_format' => null,
        'download' => null,
        'filter' => null,
        'icon' => null,
        'id' => null,
        'link_behavior' => null,
        'localization' => null,
        'readonly' => null,
        'reference' => null,
        'reference_id' => null,
        'required' => null,
        'show_map' => null,
        'show_title' => null,
        'sub_type' => null,
        'type' => null,
        'zoom_level' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'allow_multiple' => false,
        'auto_play' => false,
        'creator_name_pattern' => false,
        'date_time_format' => false,
        'download' => false,
        'filter' => false,
        'icon' => false,
        'id' => false,
        'link_behavior' => false,
        'localization' => false,
        'readonly' => false,
        'reference' => false,
        'reference_id' => false,
        'required' => false,
        'show_map' => false,
        'show_title' => false,
        'sub_type' => false,
        'type' => false,
        'zoom_level' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'allow_multiple' => 'allowMultiple',
        'auto_play' => 'autoPlay',
        'creator_name_pattern' => 'creatorNamePattern',
        'date_time_format' => 'dateTimeFormat',
        'download' => 'download',
        'filter' => 'filter',
        'icon' => 'icon',
        'id' => 'id',
        'link_behavior' => 'linkBehavior',
        'localization' => 'localization',
        'readonly' => 'readonly',
        'reference' => 'reference',
        'reference_id' => 'referenceID',
        'required' => 'required',
        'show_map' => 'showMap',
        'show_title' => 'showTitle',
        'sub_type' => 'subType',
        'type' => 'type',
        'zoom_level' => 'zoomLevel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'allow_multiple' => 'setAllowMultiple',
        'auto_play' => 'setAutoPlay',
        'creator_name_pattern' => 'setCreatorNamePattern',
        'date_time_format' => 'setDateTimeFormat',
        'download' => 'setDownload',
        'filter' => 'setFilter',
        'icon' => 'setIcon',
        'id' => 'setId',
        'link_behavior' => 'setLinkBehavior',
        'localization' => 'setLocalization',
        'readonly' => 'setReadonly',
        'reference' => 'setReference',
        'reference_id' => 'setReferenceId',
        'required' => 'setRequired',
        'show_map' => 'setShowMap',
        'show_title' => 'setShowTitle',
        'sub_type' => 'setSubType',
        'type' => 'setType',
        'zoom_level' => 'setZoomLevel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'allow_multiple' => 'getAllowMultiple',
        'auto_play' => 'getAutoPlay',
        'creator_name_pattern' => 'getCreatorNamePattern',
        'date_time_format' => 'getDateTimeFormat',
        'download' => 'getDownload',
        'filter' => 'getFilter',
        'icon' => 'getIcon',
        'id' => 'getId',
        'link_behavior' => 'getLinkBehavior',
        'localization' => 'getLocalization',
        'readonly' => 'getReadonly',
        'reference' => 'getReference',
        'reference_id' => 'getReferenceId',
        'required' => 'getRequired',
        'show_map' => 'getShowMap',
        'show_title' => 'getShowTitle',
        'sub_type' => 'getSubType',
        'type' => 'getType',
        'zoom_level' => 'getZoomLevel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('allow_multiple', $data ?? [], null);
        $this->setIfExists('auto_play', $data ?? [], null);
        $this->setIfExists('creator_name_pattern', $data ?? [], null);
        $this->setIfExists('date_time_format', $data ?? [], null);
        $this->setIfExists('download', $data ?? [], null);
        $this->setIfExists('filter', $data ?? [], null);
        $this->setIfExists('icon', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('link_behavior', $data ?? [], null);
        $this->setIfExists('localization', $data ?? [], null);
        $this->setIfExists('readonly', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('reference_id', $data ?? [], null);
        $this->setIfExists('required', $data ?? [], null);
        $this->setIfExists('show_map', $data ?? [], null);
        $this->setIfExists('show_title', $data ?? [], null);
        $this->setIfExists('sub_type', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('zoom_level', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets allow_multiple
     *
     * @return int|null
     */
    public function getAllowMultiple()
    {
        return $this->container['allow_multiple'];
    }

    /**
     * Sets allow_multiple
     *
     * @param int|null $allow_multiple allow_multiple
     *
     * @return self
     */
    public function setAllowMultiple($allow_multiple)
    {
        if (is_null($allow_multiple)) {
            throw new \InvalidArgumentException('non-nullable allow_multiple cannot be null');
        }
        $this->container['allow_multiple'] = $allow_multiple;

        return $this;
    }

    /**
     * Gets auto_play
     *
     * @return bool|null
     */
    public function getAutoPlay()
    {
        return $this->container['auto_play'];
    }

    /**
     * Sets auto_play
     *
     * @param bool|null $auto_play auto_play
     *
     * @return self
     */
    public function setAutoPlay($auto_play)
    {
        if (is_null($auto_play)) {
            throw new \InvalidArgumentException('non-nullable auto_play cannot be null');
        }
        $this->container['auto_play'] = $auto_play;

        return $this;
    }

    /**
     * Gets creator_name_pattern
     *
     * @return string|null
     */
    public function getCreatorNamePattern()
    {
        return $this->container['creator_name_pattern'];
    }

    /**
     * Sets creator_name_pattern
     *
     * @param string|null $creator_name_pattern creator_name_pattern
     *
     * @return self
     */
    public function setCreatorNamePattern($creator_name_pattern)
    {
        if (is_null($creator_name_pattern)) {
            throw new \InvalidArgumentException('non-nullable creator_name_pattern cannot be null');
        }
        $this->container['creator_name_pattern'] = $creator_name_pattern;

        return $this;
    }

    /**
     * Gets date_time_format
     *
     * @return string|null
     */
    public function getDateTimeFormat()
    {
        return $this->container['date_time_format'];
    }

    /**
     * Sets date_time_format
     *
     * @param string|null $date_time_format date_time_format
     *
     * @return self
     */
    public function setDateTimeFormat($date_time_format)
    {
        if (is_null($date_time_format)) {
            throw new \InvalidArgumentException('non-nullable date_time_format cannot be null');
        }
        $this->container['date_time_format'] = $date_time_format;

        return $this;
    }

    /**
     * Gets download
     *
     * @return bool|null
     */
    public function getDownload()
    {
        return $this->container['download'];
    }

    /**
     * Sets download
     *
     * @param bool|null $download download
     *
     * @return self
     */
    public function setDownload($download)
    {
        if (is_null($download)) {
            throw new \InvalidArgumentException('non-nullable download cannot be null');
        }
        $this->container['download'] = $download;

        return $this;
    }

    /**
     * Gets filter
     *
     * @return \OpenAPI\Client\Model\ModelSearch|null
     */
    public function getFilter()
    {
        return $this->container['filter'];
    }

    /**
     * Sets filter
     *
     * @param \OpenAPI\Client\Model\ModelSearch|null $filter filter
     *
     * @return self
     */
    public function setFilter($filter)
    {
        if (is_null($filter)) {
            throw new \InvalidArgumentException('non-nullable filter cannot be null');
        }
        $this->container['filter'] = $filter;

        return $this;
    }

    /**
     * Gets icon
     *
     * @return string|null
     */
    public function getIcon()
    {
        return $this->container['icon'];
    }

    /**
     * Sets icon
     *
     * @param string|null $icon icon
     *
     * @return self
     */
    public function setIcon($icon)
    {
        if (is_null($icon)) {
            throw new \InvalidArgumentException('non-nullable icon cannot be null');
        }
        $this->container['icon'] = $icon;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets link_behavior
     *
     * @return string|null
     */
    public function getLinkBehavior()
    {
        return $this->container['link_behavior'];
    }

    /**
     * Sets link_behavior
     *
     * @param string|null $link_behavior link_behavior
     *
     * @return self
     */
    public function setLinkBehavior($link_behavior)
    {
        if (is_null($link_behavior)) {
            throw new \InvalidArgumentException('non-nullable link_behavior cannot be null');
        }
        $this->container['link_behavior'] = $link_behavior;

        return $this;
    }

    /**
     * Gets localization
     *
     * @return array<string,\OpenAPI\Client\Model\ModelDirectoryItemLocalization>|null
     */
    public function getLocalization()
    {
        return $this->container['localization'];
    }

    /**
     * Sets localization
     *
     * @param array<string,\OpenAPI\Client\Model\ModelDirectoryItemLocalization>|null $localization localization
     *
     * @return self
     */
    public function setLocalization($localization)
    {
        if (is_null($localization)) {
            throw new \InvalidArgumentException('non-nullable localization cannot be null');
        }
        $this->container['localization'] = $localization;

        return $this;
    }

    /**
     * Gets readonly
     *
     * @return bool|null
     */
    public function getReadonly()
    {
        return $this->container['readonly'];
    }

    /**
     * Sets readonly
     *
     * @param bool|null $readonly readonly
     *
     * @return self
     */
    public function setReadonly($readonly)
    {
        if (is_null($readonly)) {
            throw new \InvalidArgumentException('non-nullable readonly cannot be null');
        }
        $this->container['readonly'] = $readonly;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference only for contentRowObjectType != null
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }
        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets reference_id
     *
     * @return string|null
     */
    public function getReferenceId()
    {
        return $this->container['reference_id'];
    }

    /**
     * Sets reference_id
     *
     * @param string|null $reference_id reference_id
     *
     * @return self
     */
    public function setReferenceId($reference_id)
    {
        if (is_null($reference_id)) {
            throw new \InvalidArgumentException('non-nullable reference_id cannot be null');
        }
        $this->container['reference_id'] = $reference_id;

        return $this;
    }

    /**
     * Gets required
     *
     * @return bool|null
     */
    public function getRequired()
    {
        return $this->container['required'];
    }

    /**
     * Sets required
     *
     * @param bool|null $required required
     *
     * @return self
     */
    public function setRequired($required)
    {
        if (is_null($required)) {
            throw new \InvalidArgumentException('non-nullable required cannot be null');
        }
        $this->container['required'] = $required;

        return $this;
    }

    /**
     * Gets show_map
     *
     * @return bool|null
     */
    public function getShowMap()
    {
        return $this->container['show_map'];
    }

    /**
     * Sets show_map
     *
     * @param bool|null $show_map show_map
     *
     * @return self
     */
    public function setShowMap($show_map)
    {
        if (is_null($show_map)) {
            throw new \InvalidArgumentException('non-nullable show_map cannot be null');
        }
        $this->container['show_map'] = $show_map;

        return $this;
    }

    /**
     * Gets show_title
     *
     * @return bool|null
     */
    public function getShowTitle()
    {
        return $this->container['show_title'];
    }

    /**
     * Sets show_title
     *
     * @param bool|null $show_title show_title
     *
     * @return self
     */
    public function setShowTitle($show_title)
    {
        if (is_null($show_title)) {
            throw new \InvalidArgumentException('non-nullable show_title cannot be null');
        }
        $this->container['show_title'] = $show_title;

        return $this;
    }

    /**
     * Gets sub_type
     *
     * @return string|null
     */
    public function getSubType()
    {
        return $this->container['sub_type'];
    }

    /**
     * Sets sub_type
     *
     * @param string|null $sub_type sub_type
     *
     * @return self
     */
    public function setSubType($sub_type)
    {
        if (is_null($sub_type)) {
            throw new \InvalidArgumentException('non-nullable sub_type cannot be null');
        }
        $this->container['sub_type'] = $sub_type;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets zoom_level
     *
     * @return string|null
     */
    public function getZoomLevel()
    {
        return $this->container['zoom_level'];
    }

    /**
     * Sets zoom_level
     *
     * @param string|null $zoom_level zoom_level
     *
     * @return self
     */
    public function setZoomLevel($zoom_level)
    {
        if (is_null($zoom_level)) {
            throw new \InvalidArgumentException('non-nullable zoom_level cannot be null');
        }
        $this->container['zoom_level'] = $zoom_level;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


