<?php
/**
 * ModelSearch
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should be careful to interpreted them as html to avoid against xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.3.0-pre.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ModelSearch Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelSearch implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'model.Search';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'keyword_ids' => 'string[]',
        'object_ids' => 'string[]',
        'object_types' => 'string[]',
        'project_ids' => 'string[]',
        'reference_ids' => 'string[]',
        'search_string' => 'string',
        'search_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'keyword_ids' => null,
        'object_ids' => null,
        'object_types' => null,
        'project_ids' => null,
        'reference_ids' => 'optional',
        'search_string' => null,
        'search_type' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'keyword_ids' => false,
        'object_ids' => false,
        'object_types' => false,
        'project_ids' => false,
        'reference_ids' => false,
        'search_string' => false,
        'search_type' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'keyword_ids' => 'keywordIds',
        'object_ids' => 'objectIds',
        'object_types' => 'objectTypes',
        'project_ids' => 'projectIds',
        'reference_ids' => 'referenceIds',
        'search_string' => 'searchString',
        'search_type' => 'searchType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'keyword_ids' => 'setKeywordIds',
        'object_ids' => 'setObjectIds',
        'object_types' => 'setObjectTypes',
        'project_ids' => 'setProjectIds',
        'reference_ids' => 'setReferenceIds',
        'search_string' => 'setSearchString',
        'search_type' => 'setSearchType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'keyword_ids' => 'getKeywordIds',
        'object_ids' => 'getObjectIds',
        'object_types' => 'getObjectTypes',
        'project_ids' => 'getProjectIds',
        'reference_ids' => 'getReferenceIds',
        'search_string' => 'getSearchString',
        'search_type' => 'getSearchType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const OBJECT_TYPES_ACCOUNT = 'Account';
    public const OBJECT_TYPES_CALENDAR = 'Calendar';
    public const OBJECT_TYPES_CALENDAR_ENTRY = 'CalendarEntry';
    public const OBJECT_TYPES_CHAT_FEED = 'ChatFeed';
    public const OBJECT_TYPES_DIRECTORY = 'Directory';
    public const OBJECT_TYPES_DIRECTORY_CONTENT_ROW = 'DirectoryContentRow';
    public const OBJECT_TYPES_GROUP = 'Group';
    public const OBJECT_TYPES_KEYWORD = 'Keyword';
    public const OBJECT_TYPES_LOCATION = 'Location';
    public const OBJECT_TYPES_LOCATION_MAP = 'LocationMap';
    public const OBJECT_TYPES_MEDIA = 'Media';
    public const OBJECT_TYPES_MEDIA_AUDIO = 'MediaAudio';
    public const OBJECT_TYPES_MEDIA_DOCUMENT = 'MediaDocument';
    public const OBJECT_TYPES_MEDIA_FOLDER = 'MediaFolder';
    public const OBJECT_TYPES_MEDIA_ICON = 'MediaIcon';
    public const OBJECT_TYPES_MEDIA_IMAGE = 'MediaImage';
    public const OBJECT_TYPES_MEDIA_OTHER = 'MediaOther';
    public const OBJECT_TYPES_MEDIA_VIDEO = 'MediaVideo';
    public const OBJECT_TYPES_MENU = 'Menu';
    public const OBJECT_TYPES_NEWS = 'News';
    public const OBJECT_TYPES_PAGE = 'Page';
    public const OBJECT_TYPES_PROJECT = 'Project';
    public const OBJECT_TYPES_STREAM = 'Stream';
    public const SEARCH_TYPE_LIVE_SEARCH = 'LiveSearch';
    public const SEARCH_TYPE_WORD_SEARCH = 'WordSearch';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getObjectTypesAllowableValues()
    {
        return [
            self::OBJECT_TYPES_ACCOUNT,
            self::OBJECT_TYPES_CALENDAR,
            self::OBJECT_TYPES_CALENDAR_ENTRY,
            self::OBJECT_TYPES_CHAT_FEED,
            self::OBJECT_TYPES_DIRECTORY,
            self::OBJECT_TYPES_DIRECTORY_CONTENT_ROW,
            self::OBJECT_TYPES_GROUP,
            self::OBJECT_TYPES_KEYWORD,
            self::OBJECT_TYPES_LOCATION,
            self::OBJECT_TYPES_LOCATION_MAP,
            self::OBJECT_TYPES_MEDIA,
            self::OBJECT_TYPES_MEDIA_AUDIO,
            self::OBJECT_TYPES_MEDIA_DOCUMENT,
            self::OBJECT_TYPES_MEDIA_FOLDER,
            self::OBJECT_TYPES_MEDIA_ICON,
            self::OBJECT_TYPES_MEDIA_IMAGE,
            self::OBJECT_TYPES_MEDIA_OTHER,
            self::OBJECT_TYPES_MEDIA_VIDEO,
            self::OBJECT_TYPES_MENU,
            self::OBJECT_TYPES_NEWS,
            self::OBJECT_TYPES_PAGE,
            self::OBJECT_TYPES_PROJECT,
            self::OBJECT_TYPES_STREAM,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSearchTypeAllowableValues()
    {
        return [
            self::SEARCH_TYPE_LIVE_SEARCH,
            self::SEARCH_TYPE_WORD_SEARCH,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('keyword_ids', $data ?? [], null);
        $this->setIfExists('object_ids', $data ?? [], null);
        $this->setIfExists('object_types', $data ?? [], null);
        $this->setIfExists('project_ids', $data ?? [], null);
        $this->setIfExists('reference_ids', $data ?? [], null);
        $this->setIfExists('search_string', $data ?? [], null);
        $this->setIfExists('search_type', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getSearchTypeAllowableValues();
        if (!is_null($this->container['search_type']) && !in_array($this->container['search_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'search_type', must be one of '%s'",
                $this->container['search_type'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets keyword_ids
     *
     * @return string[]|null
     */
    public function getKeywordIds()
    {
        return $this->container['keyword_ids'];
    }

    /**
     * Sets keyword_ids
     *
     * @param string[]|null $keyword_ids filter for objects with at least one of the provided keywords; use empty array for no keyword filter
     *
     * @return self
     */
    public function setKeywordIds($keyword_ids)
    {
        if (is_null($keyword_ids)) {
            throw new \InvalidArgumentException('non-nullable keyword_ids cannot be null');
        }
        $this->container['keyword_ids'] = $keyword_ids;

        return $this;
    }

    /**
     * Gets object_ids
     *
     * @return string[]|null
     */
    public function getObjectIds()
    {
        return $this->container['object_ids'];
    }

    /**
     * Sets object_ids
     *
     * @param string[]|null $object_ids filter for objects for provided objectIds; if array is set objectTypes must contain exactly one entry; objectIds must belong to object type set in objectTypes; private items will not be part of the result; use empty array for no type filter
     *
     * @return self
     */
    public function setObjectIds($object_ids)
    {
        if (is_null($object_ids)) {
            throw new \InvalidArgumentException('non-nullable object_ids cannot be null');
        }
        $this->container['object_ids'] = $object_ids;

        return $this;
    }

    /**
     * Gets object_types
     *
     * @return string[]|null
     */
    public function getObjectTypes()
    {
        return $this->container['object_types'];
    }

    /**
     * Sets object_types
     *
     * @param string[]|null $object_types filter for objects of provided objectTypes; objectType Group is not indexed; use empty array for no type filter
     *
     * @return self
     */
    public function setObjectTypes($object_types)
    {
        if (is_null($object_types)) {
            throw new \InvalidArgumentException('non-nullable object_types cannot be null');
        }
        $allowedValues = $this->getObjectTypesAllowableValues();
        if (array_diff($object_types, $allowedValues)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'object_types', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['object_types'] = $object_types;

        return $this;
    }

    /**
     * Gets project_ids
     *
     * @return string[]|null
     */
    public function getProjectIds()
    {
        return $this->container['project_ids'];
    }

    /**
     * Sets project_ids
     *
     * @param string[]|null $project_ids filter for project available objects; use empty array for no project filter, global objects are always supplied
     *
     * @return self
     */
    public function setProjectIds($project_ids)
    {
        if (is_null($project_ids)) {
            throw new \InvalidArgumentException('non-nullable project_ids cannot be null');
        }
        $this->container['project_ids'] = $project_ids;

        return $this;
    }

    /**
     * Gets reference_ids
     *
     * @return string[]|null
     */
    public function getReferenceIds()
    {
        return $this->container['reference_ids'];
    }

    /**
     * Sets reference_ids
     *
     * @param string[]|null $reference_ids filter for objects with at least one of the provided referenceIDs (parents); if array is set objectTypes must contain exactly one of the following entries: CalendarEntry, DirectoryContentRow; use empty array for no type filter | OR filter
     *
     * @return self
     */
    public function setReferenceIds($reference_ids)
    {
        if (is_null($reference_ids)) {
            throw new \InvalidArgumentException('non-nullable reference_ids cannot be null');
        }
        $this->container['reference_ids'] = $reference_ids;

        return $this;
    }

    /**
     * Gets search_string
     *
     * @return string|null
     */
    public function getSearchString()
    {
        return $this->container['search_string'];
    }

    /**
     * Sets search_string
     *
     * @param string|null $search_string filter for objects with provided text; can be empty when either keywordIds, objectIds, objectTypes, projectIds or referenceIds is not empty, else must have min 3 characters; LiveSearch: space separated groups of characters are treated as disjunctive regex group; WordSearch: exact match of whole words, for phrases wrap in escaped double quotes, exclude words by prepending \"-\"
     *
     * @return self
     */
    public function setSearchString($search_string)
    {
        if (is_null($search_string)) {
            throw new \InvalidArgumentException('non-nullable search_string cannot be null');
        }
        $this->container['search_string'] = $search_string;

        return $this;
    }

    /**
     * Gets search_type
     *
     * @return string|null
     */
    public function getSearchType()
    {
        return $this->container['search_type'];
    }

    /**
     * Sets search_type
     *
     * @param string|null $search_type specifies how searchString should be interpreted; use LiveSearch if searchString is empty.
     *
     * @return self
     */
    public function setSearchType($search_type)
    {
        if (is_null($search_type)) {
            throw new \InvalidArgumentException('non-nullable search_type cannot be null');
        }
        $allowedValues = $this->getSearchTypeAllowableValues();
        if (!in_array($search_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'search_type', must be one of '%s'",
                    $search_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['search_type'] = $search_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


