<?php
/**
 * PageAdminApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Polario API
 *
 * API for Polario  __Naming:__  * json properties are formatted in camel case (fooBar) besides of enums (FooBar) * route params are formatted in hyphen case (foo-bar) * query params are formatted in snake case (foo_bar) * query params could hold lists of elements if they are comma separated * enum properties are formatted in capitalized camel case (FooBar)  __Default values:__  * default values are specified for optional parameters do only apply to POST requests  __Types:__  * numbers are considered to be float values * strings that are not specified to be html formatted should be careful to interpreted them as html to avoid against xss attacks * timestamps are considered to be in unix time  __Headers:__  * ___Platform___: can be always set as header param to specify the platform of the request for the logging output
 *
 * The version of the OpenAPI document: 5.3.0-pre.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PageAdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PageAdminApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for pageAdminIdAccessGet
     *
     * Get page access configuration.
     *
     */
    public function testPageAdminIdAccessGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdAccessPatch
     *
     * Update page access configuration.
     *
     */
    public function testPageAdminIdAccessPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdContentDesktopDelete
     *
     * Delete desktop content.
     *
     */
    public function testPageAdminIdContentDesktopDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdContentDesktopGet
     *
     * Get page desktop content.
     *
     */
    public function testPageAdminIdContentDesktopGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdContentDesktopPut
     *
     * Update page desktop content.
     *
     */
    public function testPageAdminIdContentDesktopPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdContentGet
     *
     * Get page mobile content.
     *
     */
    public function testPageAdminIdContentGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdContentPut
     *
     * Update page mobile content.
     *
     */
    public function testPageAdminIdContentPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdDelete
     *
     * Delete page.
     *
     */
    public function testPageAdminIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdDesktopGet
     *
     * Get page desktop content.
     *
     */
    public function testPageAdminIdDesktopGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdGet
     *
     * Get page.
     *
     */
    public function testPageAdminIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdPatch
     *
     * Update page.
     *
     */
    public function testPageAdminIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdSettingsGet
     *
     * Get page settings.
     *
     */
    public function testPageAdminIdSettingsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminIdSettingsPut
     *
     * Update page settings.
     *
     */
    public function testPageAdminIdSettingsPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminPost
     *
     * Create page.
     *
     */
    public function testPageAdminPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminPostCountProjectIdGet
     *
     * Get page post counts for project.
     *
     */
    public function testPageAdminPostCountProjectIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminProjectIdGet
     *
     * Get page list for project.
     *
     */
    public function testPageAdminProjectIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pageAdminSyncPut
     *
     * Sync Operators for all pages.
     *
     */
    public function testPageAdminSyncPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
